name: Feature request
description: Suggest an idea for this project
title: "This is a FEATURE REQUEST for <feature>'"
labels: ["enhancement"]
assignees: ["shivradnimra"]
projects: ["@shivradnimra's Product Launch 1"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if a request issue already exists for this feature.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Feature Description
    description: Describe the solution you'd like.
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternative solutions
    description: Describe alternatives you've considered.  
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context?
    description: |
      Links? References? Anything that will give us more context about the feature you are requesting!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
- type: markdown
  attributes:
    value: "## Thanks for taking the time to fill this feature request!"
